hcloud:
  region: nbg1
  sshkeyname: key
  token: "FILLME"
  worker:
    image: ubuntu-22.04
    type: cax31
  controlplane:
    image: ubuntu-22.04
    type: cax11
controlplane:
  replicas: 1
  # head -c 32 /dev/urandom | base64
  encryptionpassphrase: "FILLME"
  version: "1.28.0"
  crunversion: "1.8.7"
  containerdversion: "1.7.3"
machinedeployment:
  replicas: 3
  version: "1.28.0"
  crunversion: "1.8.7" 
  containerdversion: "1.7.3" 
cluster:
  name: "FILLME"
addons:
  ccm:
    enabled: true
    type: hetzner
  cni:
    enabled: true
    type: flannel
  csi:
    enabled: true
    type: hetzner
    config:
      hetzner:
        # head -c 32 /dev/urandom | base64
        encryptionpassphrase: "FILLME"
  ingresscontroller:
    enabled: false
    type: nginx
    config:
      nginx:
        domains:
          - "example.com"
  certmanager:
    enabled: false
    type: certmanager
    config:
      certmanager:
        issueremail: notify@example.com
  externaldns:
    enabled: false
    type: externaldns
    config:
      externaldns:
        cloudflaretoken: "FILLME"
        txtownerid: exmaplecom
        domainFilters:
          - 'example.com'
  monitoring:
    enabled: false
    type: kubeprometheus
    config:
      kubeprometheus:
        domains:
          - grafana.example.com
        username: admin
        password: "FILLME"
  storage:
    longhorn:
      enabled: false
      username: admin
      # openssl passwd -stdin -apr1
      password: "$apr1$BrNeduMV$2N6FwqUqPzjeBbz2ZPiVg0" #password
      hostnames:
        - longhorn.example.com
  backup:
    longhorn:
      enabled: false
      backupTarget: "FILLME"
      accesskey: "FILLME"
      accesskeyid: "FILLME"
      awsendpoint: "FILLME"
  gitops:
    flux:
      enabled: false
      repository:
        name: "FILLME"
        url: "FILLME"
      secret:
        username: "FILLME"
        pat: "FILLME"
    weave:
      enabled: false
      username: "FILLME"
      # bcrypt hashed password, can be done with `gitops get bcrypt-hash` if the weave gitops cli is installed
      password: "FILLME"
      hostnames:
        - gitops.example.com