{{ with .Values.addons.csi.config }}
apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: hcloud-csi
  labels:
    {{- include "hcloud-clusterapi.labels" $ | nindent 4 }}
spec:
  clusterSelector:
    matchLabels:
      codes.danielrichter.clusterapi-hcloud.addons/csi.enabled: "true"
      codes.danielrichter.clusterapi-hcloud.addons/csi.type: "hetzner"
  repoURL: https://charts.hetzner.cloud
  chartName: hcloud-csi
  namespace: kube-system
  options:
    install:
      createNamespace: true
  version: "2.5.1"
  releaseName: hcloud-csi
  valuesTemplate: |
    fullnameOverride: hetzner-csi
    storageClasses:
    - name: hcloud
      defaultStorageClass: false
      reclaimPolicy: Delete
      allowVolumeExpansion: true
    controller:
      hcloudVolumeDefaultLocation: {{ $.Values.hcloud.region }}
      priorityClassName: system-cluster-critical
      resources:
        csiAttacher:
          limits:
            memory: 80Mi
            cpu: 50m
          requests:
            memory: 20Mi
            cpu: 10m
        csiResizer:
          limits:
            memory: 80Mi
            cpu: 50m
          requests:
            memory: 20Mi
            cpu: 10m
        csiProvisioner:
          limits:
            memory: 80Mi
            cpu: 50m
          requests:
            memory: 20Mi
            cpu: 10m
        livenessProbe:
          limits:
            memory: 80Mi
            cpu: 50m
          requests:
            memory: 20Mi
            cpu: 10m
        hcloudCSIDriver:
          limits:
            memory: 80Mi
            cpu: 50m
          requests:
            memory: 20Mi
            cpu: 10m
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: csi-hcloud
                operator: In
                values:
                - controller
            topologyKey: "kubernetes.io/hostname"
      hcloudToken:
        value: {{ $.Values.hcloud.token }}
    node:
      priorityClassName: "system-node-critical"
      resources:
        CSINodeDriverRegistrar:
          limits: 
            memory: 40Mi
            cpu: 50m
          requests: 
            memory: 20Mi
            cpu: 10m
        livenessProbe:
          limits: 
            memory: 40Mi
            cpu: 50m
          requests: 
            memory: 20Mi
            cpu: 10m
        hcloudCSIDriver:
          limits:
            memory: 80Mi
            cpu: 100m
          requests: 
            memory: 40Mi
            cpu: 10m
      hostNetwork: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "node-role.kubernetes.io/control-plane"
                operator: NotIn
                values:
                - ""
              - key: "instance.hetzner.cloud/is-root-server"
                operator: NotIn
                values:
                - "true"
---
apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: csi-extra
  labels:
    {{- include "hcloud-clusterapi.labels" $ | nindent 4 }}
spec:
  clusterSelector:
    matchLabels:
      codes.danielrichter.clusterapi-hcloud.addons/csi.enabled: "true"
      codes.danielrichter.clusterapi-hcloud.addons/csi.type: "hetzner"
  repoURL: oci://ghcr.io/danielr1996/helm-extra-deploy
  chartName: helm-extra-deploy
  namespace: kube-system
  options:
    install:
      createNamespace: true
  version: "1.0.0"
  releaseName: csi-extra
  valuesTemplate: |
    extraDeploy:
      - |
        apiVersion: v1
        kind: Secret
        metadata:
          name: encryption-secret
          namespace: kube-system
        stringData:
          encryption-passphrase: {{ .hetzner.encryptionpassphrase }}
      - |
        apiVersion: storage.k8s.io/v1
        kind: StorageClass
        metadata:
          name: hcloud-encrypted
        provisioner: csi.hetzner.cloud
        reclaimPolicy: Delete
        volumeBindingMode: WaitForFirstConsumer
        allowVolumeExpansion: true
        parameters:
          csi.storage.k8s.io/node-publish-secret-name: encryption-secret
          csi.storage.k8s.io/node-publish-secret-namespace: kube-system
{{ end }}