apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: rook-servicemonitor
  labels:
    {{- include "hcloud-clusterapi.labels" . | nindent 4 }}
spec:
  clusterSelector:
    matchLabels:
      codes.danielrichter.clusterapi-hcloud.addons/storage.enabled: "true"
      codes.danielrichter.clusterapi-hcloud.addons/storage.type: "rook"
  repoURL: oci://ghcr.io/danielr1996/helm-extra-deploy
  chartName: helm-extra-deploy
  namespace: rook-ceph
  version: "1.0.0"
  releaseName: rook-servicemonitor
  options:
    install:
      createNamespace: true
  valuesTemplate: |
    extraDeploy:
    - apiVersion: monitoring.coreos.com/v1
      kind: ServiceMonitor
      metadata:
        name: rook-ceph-exporter
        namespace: rook-ceph
        labels:
          team: rook
      spec:
        namespaceSelector:
          matchNames:
            - rook-ceph
        selector:
          matchLabels:
            app: rook-ceph-exporter
            rook_cluster: rook-ceph
            ceph_daemon_id: exporter
        endpoints:
          - port: ceph-exporter-http-metrics
            path: /metrics
            interval: 5s
    - apiVersion: monitoring.coreos.com/v1
      kind: ServiceMonitor
      metadata:
        name: rook-ceph-mgr
        namespace: rook-ceph
        labels:
          team: rook
      spec:
        namespaceSelector:
          matchNames:
            - rook-ceph
        selector:
          matchLabels:
            app: rook-ceph-mgr
            rook_cluster: rook-ceph
        endpoints:
          - port: http-metrics
            path: /metrics
            interval: 5s