apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: snapshotcontroller
  labels:
    {{- include "hcloud-clusterapi.labels" . | nindent 4 }}
spec:
  clusterSelector:
    matchLabels:
      codes.danielrichter.clusterapi-hcloud.addons/storage.enabled: "true"
      codes.danielrichter.clusterapi-hcloud.addons/storage.type: "rook"
  repoURL: https://piraeus.io/helm-charts/
  chartName: snapshot-controller
  namespace: snapshot-controller
  version: "1.8.3"
  releaseName: snapshot-controller
  options:
    install:
      createNamespace: true
