apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: stash-repository
  labels:
    {{- include "hcloud-clusterapi.labels" . | nindent 4 }}
spec:
  clusterSelector:
    matchLabels:
      addons/backup: disabled
  repoURL: oci://ghcr.io/danielr1996/helm-extra-deploy
  chartName: helm-extra-deploy
  namespace: stash
  version: "1.0.0"
  releaseName: stash-repository
  options:
    install:
      createNamespace: true
  valuesTemplate: |
    extraDeploy:
      - apiVersion: v1
        kind: Secret
        metadata:
          name: b2-secret
        type: Opaque
        stringData:
            RESTIC_PASSWORD: {{ .Values.addons.backup.password }}
            B2_ACCOUNT_ID: {{ .Values.addons.backup.b2accountid }}
            B2_ACCOUNT_KEY: {{ .Values.addons.backup.b2accountkey }}