apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: HCloudMachineTemplate
metadata:
  name: {{ include "hcloud-clusterapi.fullname" . }}-md-cax11
spec:
  template:
    spec:
      imageName: {{ .Values.hcloud.worker.image }}
      placementGroupName: md-0
      type: cax11
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: HCloudMachineTemplate
metadata:
  name: {{ include "hcloud-clusterapi.fullname" . }}-md-cax21
spec:
  template:
    spec:
      imageName: {{ .Values.hcloud.worker.image }}
      placementGroupName: md-0
      type: cax21