apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: HCloudRemediationTemplate
metadata:
  name: {{ include "hcloud-clusterapi.fullname" . }}-md
  labels:
    {{- include "hcloud-clusterapi.labels" . | nindent 4 }}
spec:
  template:
    spec:
      strategy:
        retryLimit: 1
        timeout: 180s
        type: Reboot