apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: HCloudMachineTemplate
metadata:
  name: {{ include "hcloud-clusterapi.fullname" . }}-cp-{{ .Values.hcloud.controlplane.type }}
  labels:
    {{- include "hcloud-clusterapi.labels" . | nindent 4 }}
spec:
  template:
    spec:
      imageName: {{ .Values.hcloud.controlplane.image }}
      placementGroupName: control-plane
      type: {{ .Values.hcloud.controlplane.type }}