apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: HetznerCluster
metadata:
  name: {{ include "hcloud-clusterapi.fullname" . }}
  labels:
    {{- include "hcloud-clusterapi.labels" . | nindent 4 }}
spec:
  controlPlaneEndpoint:
    host: ""
    port: 443
  controlPlaneLoadBalancer:
    region: {{ .Values.hcloud.region }}
  controlPlaneRegions:
  - {{ .Values.hcloud.region }}
  hcloudNetwork:
    enabled: false
  hcloudPlacementGroups:
  - name: control-plane
    type: spread
  - name: md-0
    type: spread
  hetznerSecretRef:
    key:
      hcloudToken: hcloud
    name: {{ include "hcloud-clusterapi.fullname" . }}
  sshKeys:
    hcloud:
    - name: {{ .Values.hcloud.sshkeyname }}