apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineHealthCheck
metadata:
  name: {{ include "hcloud-clusterapi.fullname" . }}-md
spec:
  clusterName: {{ .Values.cluster.name }}
  maxUnhealthy: 100%
  nodeStartupTimeout: 10m
  remediationTemplate:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: HCloudRemediationTemplate
    name: {{ include "hcloud-clusterapi.fullname" . }}-md
  selector:
    matchLabels:
      nodepool: {{ include "hcloud-clusterapi.fullname" . }}-md
  unhealthyConditions:
  - status: Unknown
    timeout: 180s
    type: Ready
  - status: "False"
    timeout: 180s
    type: Ready