apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  labels:
    nodepool: {{ include "hcloud-clusterapi.fullname" . }}-md
  name: {{ include "hcloud-clusterapi.fullname" . }}
  labels:
    {{- include "hcloud-clusterapi.labels" . | nindent 4 }}
spec:
  clusterName: {{ .Values.cluster.name }}
  replicas: {{ .Values.machinedeployment.replicas }}
  selector:
    matchLabels: null
  template:
    metadata:
      labels:
        {{- include "hcloud-clusterapi.labels" . | nindent 8 }}
        nodepool: {{ include "hcloud-clusterapi.fullname" . }}-md
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: {{ include "hcloud-clusterapi.fullname" . }}
      clusterName: {{ .Values.cluster.name }}
      failureDomain: {{ .Values.hcloud.region }}
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: HCloudMachineTemplate
        name: {{ include "hcloud-clusterapi.fullname" . }}-md-{{ .Values.hcloud.worker.type }}
      version: {{ .Values.machinedeployment.version }}
