apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hcloud-clusterapi.fullname" . }}
  labels:
    clusterctl.cluster.x-k8s.io/move: ""
    {{- include "hcloud-clusterapi.labels" . | nindent 4 }}
type: Opaque
stringData:
    hcloud: {{ .Values.hcloud.token }}

