apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: stash-release
  labels:
    {{- include "hcloud-clusterapi.labels" . | nindent 4 }}
spec:
  clusterSelector:
    matchLabels:
      addons/backup: disabled
  repoURL: https://charts.appscode.com/stable/
  chartName: stash
  namespace: stash
  version: "v2023.08.18"
  releaseName: stash-release
  options:
    install:
      createNamespace: true
  valuesTemplate: |
    global:
      licenseSecretName: license
    fullnameOverride: stash
    features:
        community: true
