{{ with .Values.addons.gitops.flux }}
apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: flux
  labels:
    {{- include "hcloud-clusterapi.labels" $ | nindent 4 }}
spec:
  clusterSelector:
    matchLabels:
      codes.danielrichter.clusterapi-hcloud.addons/gitops.flux.enabled: "true"
  repoURL: https://fluxcd-community.github.io/helm-charts
  chartName: flux2
  namespace: flux-system
  options:
    install:
      createNamespace: true
  version: "2.11.1"
  releaseName: flux
  valuesTemplate: |
    extraObjects:
      - apiVersion: source.toolkit.fluxcd.io/v1
        kind: GitRepository
        metadata:
          name: flux-repo
          namespace: flux-system
        spec:
          interval: 1m0s
          ref:
            branch: main
          secretRef:
            name: flux-pat
          url: "{{ .repository }}"
      - apiVersion: v1
        kind: Secret
        metadata:
          name: flux-pat
          namespace: flux-system
        stringData:
          username: "{{ .username }}"
          password: "{{ .pat }}"
      - apiVersion: kustomize.toolkit.fluxcd.io/v1
        kind: Kustomization
        metadata:
          name: flux-kustomization
          namespace: flux-system
        spec:
          interval: 1m
          targetNamespace: flux-system
          sourceRef:
            kind: GitRepository
            name: flux-repo
          path: "./values"
          prune: true
          timeout: 1m
{{ end }}