{{ with .Values.addons.gitops.weave }}
apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: weave
  labels:
    {{- include "hcloud-clusterapi.labels" $ | nindent 4 }}
spec:
  clusterSelector:
    matchLabels:
      codes.danielrichter.clusterapi-hcloud.addons/gitops.weave.enabled: "true"
  repoURL: oci://ghcr.io/weaveworks/charts
  chartName: weave-gitops
  namespace: flux-system
  options:
    install:
      createNamespace: true
  version: "4.0.36"
  releaseName: weave
  valuesTemplate: |
    adminUser:
      create: true
      passwordHash: {{ .password }}
      username: {{ .username }}
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
       - host: {{ index .hostnames 0 }}
         paths:
           - path: /
             pathType: ImplementationSpecific
      tls:
        - secretName: {{ index .hostnames 0 }}
          hosts:
            - {{ index .hostnames 0 }}
---
apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: weave-extra
  labels:
    {{- include "hcloud-clusterapi.labels" $ | nindent 4 }}
spec:
  clusterSelector:
    matchLabels:
      codes.danielrichter.clusterapi-hcloud.addons/storage.longhorn.enabled: "true"
  repoURL: oci://ghcr.io/danielr1996/helm-extra-deploy
  chartName: helm-extra-deploy
  namespace: flux-system
  version: "1.0.0"
  releaseName: weave-extra
  options:
    install:
      createNamespace: true
  valuesTemplate: |
    extraDeploy:
        - apiVersion: linkbee.danielrichter.codes/v1alpha
          kind: DashboardEntry
          metadata:
            name: weave
          spec:
            title: Weave GitOps
            description: Flux Dashboard
            url: https://gitops.danielrichter.codes
            icon:
              location: https://www.weave.works/assets/favicon/favicon_300px.png
              external: true
{{ end }}