apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: velero 
  labels:
    {{- include "hcloud-clusterapi.labels" . | nindent 4 }}
spec:
  clusterSelector:
    matchLabels:
      addons/backup: enabled
  repoURL: https://vmware-tanzu.github.io/helm-charts 
  chartName: velero 
  namespace: velero
  version: "5.0.2"
  releaseName: velero
  options:
    install:
      createNamespace: true
  valuesTemplate: |
    fullnameOverride: velero
    configuration:
        backupStorageLocation:
        - name: backblaze
          provider: {{ .Values.addons.backup.provider }}
          bucket: {{ .Values.addons.backup.provider }}
          default: true
          config:
            region: {{ .Values.addons.backup.region }}
            s3Url: {{ .Values.addons.backup.s3Url }}
    credentials:
        useSecret: true
        secretContents:
          cloud: |
            [default]
            aws_access_key_id = {{ .Values.addons.backup.aws_access_key_id }}
            aws_secret_access_key = {{ .Values.addons.backup.aws_secret_access_key }}
    kubectl:
        image:
            tag: 1.27.5
    snapshotsEnabled: false
    features: EnableCSI
    deployNodeAgent: true
    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.7.0
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /target
          name: plugins
      - name: velero-plugin-for-csi
        image: velero/velero-plugin-for-csi:v0.6.0-rc.1
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /target
          name: plugins