apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: flannel
  labels:
    {{- include "hcloud-clusterapi.labels" . | nindent 4 }}
spec:
  clusterSelector:
    matchLabels:
      codes.danielrichter.clusterapi-hcloud.addons/cni.enabled: "true"
      codes.danielrichter.clusterapi-hcloud.addons/cni.type: "flannel"
  repoURL: https://flannel-io.github.io/flannel/
  chartName: flannel
  namespace: kube-system
  version: "v0.22.1"
  releaseName: flannel
  options:
    install:
      createNamespace: true
  valuesTemplate: |
    fullnameOverride: cni-flannel